os: linux
dist: xenial
env:
  global:
    - docker_repository=mlbench

jobs:
  include:
    - stage: tests
      language: python
      python: 3.7
      services: docker

      install:
        - pip install tox

      name: "Black linting"
      script: env TOXENV=black tox

    - script: env TOXENV=isort tox
      language: python
      python: 3.7
      name: "Isort linting"

    - script: env TOXENV=py37 tox
      language: python
      python: 3.7
      name: "Tests (Python 3.7) + coverage"
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - script: env TOXENV=docs tox
      language: python
      python: 3.7
      name: "Documentation"

    - stage: build docker
      services: docker
      language: shell
      install: true
      name: "Build docker image (Branch)"
      before_script: echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      script:
        - docker build -f Docker/Dockerfile -t ${docker_repository}/mlbench_master:travis-ci-test .

    - stage: deploy develop
      if: branch = develop
      language: shell
      services: docker
      name: "Build & deploy docker image (latest)"
      before_script:
        - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
        - docker pull ${docker_repository}/mlbench_master:travis-ci-test
        - docker tag ${docker_repository}/mlbench_master:travis-ci-test ${docker_repository}/mlbench_master:develop
      script:
        - docker push ${docker_repository}/mlbench_master:develop

stages:
  - tests
  - docs
  - build docker
  - deploy develop
