# Generated by Django 2.0.8 on 2018-10-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180910_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelrun',
            name='image',
            field=models.CharField(default='mlbench/mlbench_worker', max_length=100),
        ),
    ]
