# Generated by Django 2.0.8 on 2018-10-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_modelrun_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelrun',
            name='command',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='modelrun',
            name='run_on_all_nodes',
            field=models.BooleanField(default=False),
        ),
    ]
