# Generated by Django 2.0.8 on 2019-02-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20181018_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelrun',
            name='gpu_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
