# Generated by Django 2.0.8 on 2019-04-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_modelrun_gpu_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelrun",
            name="light_target",
            field=models.BooleanField(default=False),
        ),
    ]
