# Generated by Django 2.0.8 on 2020-04-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_auto_20191223_1348"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelrun",
            name="backend",
            field=models.CharField(
                choices=[("mpi", "mpi"), ("nccl", "nccl"), ("gloo", "gloo")],
                default="mpi",
                max_length=20,
            ),
        ),
    ]
