# Generated by Django 2.0.8 on 2020-05-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_modelrun_backend"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelrun",
            name="use_horovod",
            field=models.BooleanField(default=False),
        ),
    ]
