name: deploy-mlbench-dashboard

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  deploy-master-image:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: "Login to DockerHub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: "Build docker image"
        run: |
          docker build -f Docker/Dockerfile -t mlbench/mlbench_master:latest . && \
          docker push mlbench/mlbench_master:latest